export const FETCH_CHARACTERS_REQUEST = "FETCH_CHARACTERS_REQUEST";
export const FETCH_CHARACTERS_SUCCESS = "FETCH_CHARACTERS_SUCCESS";
export const FETCH_CHARACTERS_FAILURE = "FETCH_CHARACTERS_FAILURE";

export const FETCH_DEATH_REQUEST = "FETCH_DEATH_REQUEST";
export const FETCH_DEATH_SUCCESS = "FETCH_DEATH_SUCCESS";
export const FETCH_DEATH_FAILURE = "FETCH_DEATH_FAILURE";

export const FETCH_QUOTE_REQUEST = "FETCH_QUOTE_REQUEST";
export const FETCH_QUOTE_SUCCESS = "FETCH_QUOTE_SUCCESS";
export const FETCH_QUOTE_FAILURE = "FETCH_QUOTE_FAILURE";
